main = ".open-next/worker.js"
name = "mishuellitas"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[build]
command = "npm run build"

